### ISSUE TITLE
[suggestion] official Lemmy community

### ISSUE THREAD

**Issue by BluePixel4k** [GrapheneOS/infrastructure#6]
Have you ever thought about opening an official [Lemmy](https://join-lemmy.org/) community instead of Matrix (and Reddit)?
This would have a big advantage that questions are not asked twice so often and others can find and comment on them better later.

I would be happy if I consider it, because at Matrix many questions go under.

Lemmy is an open source decentralised alternative to Reddit.

There is already a Lemmy GrapheneOS community, but it is unofficial and not really known. ([https://lemmy.ml/c/grapheneos](https://lemmy.ml/c/grapheneos))

**Comment by Zanthed** [comment]
That Lemmy is reserved and was used just for announcements but since it's un-used and moderation tools are lackluster there, we've just kept it reserved. I don't think Lemmy is a good choice either.

**Comment by BluePixel4k** [comment]
Sad, would be happy if there is an alternative Matrix community option in the future. Because for me a chat app is just too confusing with thousands of people.

BTW: With Lemmy there is the possibility of self-hosted.

But thanks for your great work on GrapheneOS!

**Comment by BluePixel4k** [comment]
Closed, because the Forum https://discuss.grapheneos.org/ was released.
